<?php
require_once __DIR__ . '/../includes/functions.php';
require_login();
verify_csrf();
$pageTitle='Parking Control';
if(isset($_GET['checkout'])){$id=(int)$_GET['checkout'];$stmt=db()->prepare('SELECT * FROM parking_records WHERE id=? AND status="Active"');$stmt->execute([$id]);$record=$stmt->fetch();if($record){$out=date('Y-m-d H:i:s');$fee=calculate_fee($record['check_in'],$out);db()->prepare('UPDATE parking_records SET check_out=?, status="Completed", fee=? WHERE id=?')->execute([$out,$fee,$id]);db()->prepare('UPDATE parking_slots SET status="Available" WHERE id=?')->execute([$record['slot_id']]);flash('success','Vehicle checked out. Fee: $'.number_format($fee,2));}redirect('/pages/parking.php');}
if($_SERVER['REQUEST_METHOD']==='POST'){$vehicleId=(int)$_POST['vehicle_id'];$stmt=db()->prepare('SELECT ve.*, vi.id visitor_id FROM vehicles ve JOIN visitors vi ON vi.id=ve.visitor_id WHERE ve.id=?');$stmt->execute([$vehicleId]);$vehicle=$stmt->fetch();if(!$vehicle){flash('danger','Vehicle not found.');redirect('/pages/parking.php');}$active=db()->prepare('SELECT COUNT(*) FROM parking_records WHERE vehicle_id=? AND status="Active"');$active->execute([$vehicleId]);if((int)$active->fetchColumn()>0){flash('warning','This vehicle is already parked.');redirect('/pages/parking.php');}$slot=auto_allocate_slot($vehicle['vehicle_type']);if(!$slot){flash('danger','No available parking slot found.');redirect('/pages/parking.php');}db()->prepare('INSERT INTO parking_records (visitor_id, vehicle_id, slot_id, notes) VALUES (?,?,?,?)')->execute([$vehicle['visitor_id'],$vehicleId,$slot['id'],trim($_POST['notes']??'')]);db()->prepare('UPDATE parking_slots SET status="Occupied" WHERE id=?')->execute([$slot['id']]);flash('success','Check-in completed. Allocated slot '.$slot['slot_code'].'.');redirect('/pages/parking.php');}
$vehicles=db()->query('SELECT ve.id, ve.plate_number, ve.vehicle_type, vi.full_name FROM vehicles ve JOIN visitors vi ON vi.id=ve.visitor_id ORDER BY ve.plate_number')->fetchAll();
$records=db()->query('SELECT pr.*, vi.full_name, ve.plate_number, ps.slot_code FROM parking_records pr JOIN visitors vi ON vi.id=pr.visitor_id JOIN vehicles ve ON ve.id=pr.vehicle_id JOIN parking_slots ps ON ps.id=pr.slot_id WHERE pr.status="Active" ORDER BY pr.check_in DESC')->fetchAll();
require __DIR__ . '/../includes/header.php';
?>
<div class="row g-4"><div class="col-lg-4"><div class="card p-4"><h1 class="h4">New Vehicle Check-in</h1><form method="post"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><div class="mb-3"><label class="form-label">Vehicle</label><select class="form-select" name="vehicle_id" required><?php foreach($vehicles as $v): ?><option value="<?= $v['id'] ?>"><?= e($v['plate_number'].' - '.$v['full_name'].' ('.$v['vehicle_type'].')') ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="4"></textarea></div><button class="btn btn-primary w-100"><i class="fa-solid fa-right-to-bracket me-1"></i> Auto Allocate Slot</button></form></div></div><div class="col-lg-8"><div class="card p-4"><h2 class="h4">Active Parking</h2><div class="table-responsive"><table class="table"><thead><tr><th>Visitor</th><th>Plate</th><th>Slot</th><th>Check-in</th><th>Current Fee</th><th class="no-print">Action</th></tr></thead><tbody><?php foreach($records as $r): ?><tr><td><?= e($r['full_name']) ?></td><td><?= e($r['plate_number']) ?></td><td><?= e($r['slot_code']) ?></td><td><?= e($r['check_in']) ?></td><td>$<?= number_format(calculate_fee($r['check_in']),2) ?></td><td class="no-print"><a class="btn btn-sm btn-success" data-confirm="Check out this vehicle?" href="?checkout=<?= $r['id'] ?>">Check out</a></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
