<?php
require_once __DIR__ . '/../includes/functions.php';
require_login();
verify_csrf();
$pageTitle='Parking Slots';$edit=null;
if(isset($_GET['delete'])){db()->prepare('DELETE FROM parking_slots WHERE id=?')->execute([(int)$_GET['delete']]);flash('success','Slot deleted.');redirect('/pages/slots.php');}
if(isset($_GET['edit'])){$stmt=db()->prepare('SELECT * FROM parking_slots WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){$data=[strtoupper(trim($_POST['slot_code'])),$_POST['slot_type'],$_POST['status']];if(!empty($_POST['id'])){$data[]=(int)$_POST['id'];db()->prepare('UPDATE parking_slots SET slot_code=?, slot_type=?, status=? WHERE id=?')->execute($data);flash('success','Slot updated.');}else{db()->prepare('INSERT INTO parking_slots (slot_code, slot_type, status) VALUES (?,?,?)')->execute($data);flash('success','Slot added.');}redirect('/pages/slots.php');}
$slots=db()->query('SELECT * FROM parking_slots ORDER BY slot_code')->fetchAll();require __DIR__ . '/../includes/header.php';
?>
<div class="row g-4"><div class="col-lg-4"><div class="card p-4"><h1 class="h4"><?= $edit?'Edit Slot':'Add Slot' ?></h1><form method="post"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><div class="mb-3"><label class="form-label">Slot code</label><input class="form-control text-uppercase" name="slot_code" value="<?= e($edit['slot_code']??'') ?>" required></div><div class="mb-3"><label class="form-label">Type</label><select class="form-select" name="slot_type"><?php foreach(['Car','Motorcycle','Van','Truck','Other'] as $type): ?><option <?= (($edit['slot_type']??'Car')===$type)?'selected':'' ?>><?= $type ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['Available','Occupied','Maintenance'] as $status): ?><option <?= (($edit['status']??'Available')===$status)?'selected':'' ?>><?= $status ?></option><?php endforeach; ?></select></div><button class="btn btn-primary w-100">Save Slot</button></form></div></div><div class="col-lg-8"><div class="card p-4"><h2 class="h4">Parking Slot Inventory</h2><div class="table-responsive"><table class="table"><thead><tr><th>Code</th><th>Type</th><th>Status</th><th class="no-print">Actions</th></tr></thead><tbody><?php foreach($slots as $s): ?><tr><td><?= e($s['slot_code']) ?></td><td><?= e($s['slot_type']) ?></td><td><span class="badge <?= $s['status']==='Available'?'badge-soft-success':($s['status']==='Maintenance'?'badge-soft-warning':'badge-soft-danger') ?>"><?= e($s['status']) ?></span></td><td class="no-print"><a class="btn btn-sm btn-outline-primary" href="?edit=<?= $s['id'] ?>">Edit</a> <a class="btn btn-sm btn-outline-danger" data-confirm="Delete this slot?" href="?delete=<?= $s['id'] ?>">Delete</a></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
