<?php
require_once __DIR__ . '/../includes/functions.php';
require_login();
verify_csrf();
$pageTitle='Vehicles';
$edit=null;
if(isset($_GET['delete'])){db()->prepare('DELETE FROM vehicles WHERE id=?')->execute([(int)$_GET['delete']]);flash('success','Vehicle deleted.');redirect('/pages/vehicles.php');}
if(isset($_GET['edit'])){$stmt=db()->prepare('SELECT * FROM vehicles WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}
if($_SERVER['REQUEST_METHOD']==='POST'){$data=[(int)$_POST['visitor_id'],strtoupper(trim($_POST['plate_number'])),$_POST['vehicle_type'],trim($_POST['color']),trim($_POST['model'])];if(!empty($_POST['id'])){$data[]=(int)$_POST['id'];db()->prepare('UPDATE vehicles SET visitor_id=?, plate_number=?, vehicle_type=?, color=?, model=? WHERE id=?')->execute($data);flash('success','Vehicle updated.');}else{db()->prepare('INSERT INTO vehicles (visitor_id, plate_number, vehicle_type, color, model) VALUES (?,?,?,?,?)')->execute($data);flash('success','Vehicle added.');}redirect('/pages/vehicles.php');}
$visitors=db()->query('SELECT id, full_name FROM visitors ORDER BY full_name')->fetchAll();
$vehicles=db()->query('SELECT ve.*, vi.full_name FROM vehicles ve JOIN visitors vi ON vi.id=ve.visitor_id ORDER BY ve.created_at DESC')->fetchAll();
require __DIR__ . '/../includes/header.php';
?>
<div class="row g-4"><div class="col-lg-4"><div class="card p-4"><h1 class="h4"><?= $edit?'Edit Vehicle':'Add Vehicle' ?></h1><form method="post"><input type="hidden" name="csrf_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><div class="mb-3"><label class="form-label">Visitor</label><select class="form-select" name="visitor_id" required><?php foreach($visitors as $v): ?><option value="<?= $v['id'] ?>" <?= (($edit['visitor_id']??'')==$v['id'])?'selected':'' ?>><?= e($v['full_name']) ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Plate number</label><input class="form-control text-uppercase" name="plate_number" value="<?= e($edit['plate_number']??'') ?>" required></div><div class="mb-3"><label class="form-label">Vehicle type</label><select class="form-select" name="vehicle_type"><?php foreach(['Car','Motorcycle','Van','Truck','Other'] as $type): ?><option <?= (($edit['vehicle_type']??'Car')===$type)?'selected':'' ?>><?= $type ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label">Color</label><input class="form-control" name="color" value="<?= e($edit['color']??'') ?>" required></div><div class="mb-3"><label class="form-label">Model</label><input class="form-control" name="model" value="<?= e($edit['model']??'') ?>"></div><button class="btn btn-primary w-100">Save Vehicle</button></form></div></div><div class="col-lg-8"><div class="card p-4"><h2 class="h4">Registered Vehicles</h2><div class="table-responsive"><table class="table"><thead><tr><th>Plate</th><th>Visitor</th><th>Type</th><th>Color</th><th class="no-print">Actions</th></tr></thead><tbody><?php foreach($vehicles as $v): ?><tr><td><?= e($v['plate_number']) ?></td><td><?= e($v['full_name']) ?></td><td><?= e($v['vehicle_type']) ?></td><td><?= e($v['color']) ?></td><td class="no-print"><a class="btn btn-sm btn-outline-primary" href="?edit=<?= $v['id'] ?>">Edit</a> <a class="btn btn-sm btn-outline-danger" data-confirm="Delete this vehicle?" href="?delete=<?= $v['id'] ?>">Delete</a></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
<?php require __DIR__ . '/../includes/footer.php'; ?>
